import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { renderHtml, renderMarkdown, renderMermaid, renderReport, renderSarif, writeReports } from '../src/render.js';
import type { ClaimResult, ProofspecReport } from '../src/types.js';

function report(claims: ClaimResult[] = [verifiedClaim()]): ProofspecReport {
  return {
    reportVersion: 1,
    runId: 'proof_render',
    generatedAt: '2026-07-17T12:00:00.000Z',
    project: { name: 'Fixture <script>alert(1)</script>' },
    configFile: 'proofspec.json',
    ledger: { path: './ledger.db', valid: true, receiptsChecked: 1 },
    summary: {
      total: claims.length,
      verified: claims.filter((item) => item.effectiveStatus === 'verified').length,
      failed: claims.filter((item) => item.effectiveStatus === 'failed').length,
      unknown: claims.filter((item) => item.effectiveStatus === 'unknown').length,
      unsupported: claims.filter((item) => item.effectiveStatus === 'unsupported').length,
      blocked: claims.filter((item) => item.effectiveStatus === 'blocked').length,
      evidenceChecks: claims.flatMap((item) => item.evidence).length,
      satisfiedEvidence: claims.flatMap((item) => item.evidence).filter((item) => item.verdict === 'satisfied').length,
      gatePassed: claims.filter((item) => item.severity === 'error').every((item) => item.effectiveStatus === 'verified'),
      strictGatePassed: claims.every((item) => item.effectiveStatus === 'verified'),
    },
    claims,
    reportDigest: 'd'.repeat(64),
  };
}

function verifiedClaim(overrides: Partial<ClaimResult> = {}): ClaimResult {
  return {
    id: 'documented',
    statement: 'The README explains A | B.',
    severity: 'error',
    policy: { mode: 'all' },
    directStatus: 'verified',
    effectiveStatus: 'verified',
    evidence: [{
      id: 'readme', verdict: 'satisfied', evidenceClass: 'configured_verifier', summary: 'Found <needle>.', evidence: {},
      contractId: 'contract', observationId: 'observation', evidenceHash: 'a'.repeat(64), previousHash: null,
      receiptHash: 'b'.repeat(64), observedAt: '2026-07-17T12:00:00.000Z',
    }],
    dependsOn: [], blockedBy: [], limitations: ['Presence is not quality.'], tags: ['docs'],
    ...overrides,
  };
}

test('JSON output is parseable and newline terminated', () => {
  const output = renderReport(report(), 'json');
  assert.equal(JSON.parse(output).runId, 'proof_render');
  assert.equal(output.endsWith('\n'), true);
});

test('Markdown includes gate, claims, evidence, receipt, and limitations', () => {
  const output = renderMarkdown(report());
  assert.match(output, /Gate: \*\*PASS\*\*/);
  assert.match(output, /documented/);
  assert.match(output, /Receipt:/);
  assert.match(output, /Presence is not quality/);
});

test('Markdown escapes table pipes', () => {
  assert.match(renderMarkdown(report()), /A \\| B/);
});

test('HTML escapes all report-controlled markup', () => {
  const output = renderHtml(report());
  assert.doesNotMatch(output, /<script>alert\(1\)<\/script>/);
  assert.match(output, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/);
  assert.match(output, /Found &lt;needle&gt;/);
});

test('HTML is standalone and explicitly noindex', () => {
  const output = renderHtml(report());
  assert.match(output, /^<!doctype html>/);
  assert.match(output, /name="robots" content="noindex"/);
  assert.match(output, /Generated by Proofspec 0\.1\.0/);
});

test('Mermaid renders dependency edges and status classes', () => {
  const root = verifiedClaim({ id: 'root', statement: 'Root claim.' });
  const leaf = verifiedClaim({ id: 'leaf', statement: 'Leaf "claim".', dependsOn: ['root'], blockedBy: ['root'], effectiveStatus: 'blocked' });
  const output = renderMermaid(report([root, leaf]));
  assert.match(output, /claim_root --> claim_leaf/);
  assert.match(output, /class claim_leaf blocked/);
  assert.doesNotMatch(output, /Leaf "claim"/);
});

test('Mermaid node IDs sanitize punctuation', () => {
  const output = renderMermaid(report([verifiedClaim({ id: 'release-v1.0' })]));
  assert.match(output, /claim_release_v1_0/);
});

test('SARIF emits only non-verified claims', () => {
  const failing = verifiedClaim({ id: 'release', statement: 'Release is visible.', severity: 'warning', directStatus: 'failed', effectiveStatus: 'failed' });
  const parsed = JSON.parse(renderSarif(report([verifiedClaim(), failing])));
  assert.equal(parsed.version, '2.1.0');
  assert.equal(parsed.runs[0].results.length, 1);
  assert.equal(parsed.runs[0].results[0].ruleId, 'proofspec/release');
  assert.equal(parsed.runs[0].results[0].level, 'warning');
});

test('SARIF reports blocked dependencies in the message', () => {
  const blocked = verifiedClaim({ id: 'leaf', directStatus: 'verified', effectiveStatus: 'blocked', dependsOn: ['root'], blockedBy: ['root'] });
  const parsed = JSON.parse(renderSarif(report([blocked])));
  assert.match(parsed.runs[0].results[0].message.text, /blocked by root/);
});

test('writeReports writes every selected format', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'proofspec-reports-'));
  const paths = await writeReports(report(), directory, ['json', 'markdown', 'html', 'mermaid', 'sarif']);
  assert.equal(paths.length, 5);
  for (const path of paths) assert.ok((await readFile(path, 'utf8')).length > 20);
});

test('writeReports deduplicates requested formats', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'proofspec-reports-'));
  const paths = await writeReports(report(), directory, ['json', 'json']);
  assert.deepEqual(paths, [join(directory, 'proofspec-report.json')]);
});

test('renderReport dispatches all five formats', () => {
  for (const format of ['json', 'markdown', 'html', 'mermaid', 'sarif'] as const) {
    assert.ok(renderReport(report(), format).length > 20, format);
  }
});
