import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ClaimResult, ClaimStatus, ProofspecReport, ReportFormat } from './types.js';

const STATUS_ICON: Record<ClaimStatus, string> = {
  verified: '✓', failed: '✕', unknown: '?', unsupported: '∅', blocked: '⊘',
};

export function renderReport(report: ProofspecReport, format: ReportFormat): string {
  switch (format) {
    case 'json': return `${JSON.stringify(report, null, 2)}\n`;
    case 'markdown': return renderMarkdown(report);
    case 'html': return renderHtml(report);
    case 'mermaid': return renderMermaid(report);
    case 'sarif': return renderSarif(report);
  }
}

export async function writeReports(report: ProofspecReport, outputDir: string, formats: ReportFormat[] = ['json', 'markdown', 'html', 'mermaid', 'sarif']): Promise<string[]> {
  await mkdir(outputDir, { recursive: true });
  const extension: Record<ReportFormat, string> = { json: 'json', markdown: 'md', html: 'html', mermaid: 'mmd', sarif: 'sarif' };
  const paths: string[] = [];
  for (const format of [...new Set(formats)]) {
    const path = join(outputDir, `proofspec-report.${extension[format]}`);
    await writeFile(path, renderReport(report, format), 'utf8');
    paths.push(path);
  }
  return paths;
}

export function renderMarkdown(report: ProofspecReport): string {
  const lines = [
    `# Proofspec report — ${report.project.name}`,
    '',
    `Generated: ${report.generatedAt}`,
    `Gate: **${report.summary.gatePassed ? 'PASS' : 'FAIL'}**`,
    `Ledger: **${report.ledger.valid ? 'valid' : 'invalid'}** (${report.ledger.receiptsChecked} receipts checked)`,
    `Report digest: \`${report.reportDigest}\``,
    '',
    '| Status | Claim | Severity | Evidence | Dependencies |',
    '|---|---|---|---:|---|',
    ...report.claims.map((claim) => `| ${STATUS_ICON[claim.effectiveStatus]} ${claim.effectiveStatus} | ${escapeMarkdown(claim.statement)} | ${claim.severity} | ${claim.evidence.length} | ${claim.dependsOn.join(', ') || '—'} |`),
    '',
  ];
  for (const claim of report.claims) lines.push(...claimMarkdown(claim));
  lines.push('---', '', 'Generated by [Proofspec](https://github.com/christian140903-sudo/proofspec). A satisfied verifier proves only its configured observation.', '');
  return `${lines.join('\n')}\n`;
}

export function renderMermaid(report: ProofspecReport): string {
  const lines = ['flowchart LR'];
  for (const claim of report.claims) {
    lines.push(`  ${nodeId(claim.id)}["${escapeMermaid(`${STATUS_ICON[claim.effectiveStatus]} ${claim.id}: ${claim.statement}`)}"]`);
  }
  for (const claim of report.claims) {
    for (const dependency of claim.dependsOn) lines.push(`  ${nodeId(dependency)} --> ${nodeId(claim.id)}`);
  }
  for (const claim of report.claims) lines.push(`  class ${nodeId(claim.id)} ${claim.effectiveStatus}`);
  lines.push(
    '  classDef verified fill:#123b2d,stroke:#53e6a7,color:#effff8',
    '  classDef failed fill:#401c22,stroke:#ff8f96,color:#fff1f2',
    '  classDef unknown fill:#3b3019,stroke:#ffc66d,color:#fff8e8',
    '  classDef unsupported fill:#242936,stroke:#8e9aaf,color:#f0f3f8',
    '  classDef blocked fill:#2d2341,stroke:#a879ff,color:#f6f0ff',
  );
  return `${lines.join('\n')}\n`;
}

export function renderSarif(report: ProofspecReport): string {
  const failing = report.claims.filter((claim) => claim.effectiveStatus !== 'verified');
  const sarif = {
    version: '2.1.0',
    $schema: 'https://json.schemastore.org/sarif-2.1.0.json',
    runs: [{
      tool: {
        driver: {
          name: 'Proofspec',
          informationUri: 'https://github.com/christian140903-sudo/proofspec',
          version: '0.1.0',
          rules: failing.map((claim) => ({
            id: `proofspec/${claim.id}`,
            shortDescription: { text: claim.statement },
            helpUri: 'https://github.com/christian140903-sudo/proofspec/blob/main/docs/CONFIG.md',
          })),
        },
      },
      results: failing.map((claim) => ({
        ruleId: `proofspec/${claim.id}`,
        level: claim.severity === 'error' ? 'error' : claim.severity === 'warning' ? 'warning' : 'note',
        message: { text: `${claim.effectiveStatus}: ${claim.statement}${claim.blockedBy.length ? `; blocked by ${claim.blockedBy.join(', ')}` : ''}` },
        locations: [{ physicalLocation: { artifactLocation: { uri: report.configFile }, region: { startLine: 1 } } }],
      })),
    }],
  };
  return `${JSON.stringify(sarif, null, 2)}\n`;
}

export function renderHtml(report: ProofspecReport): string {
  const cards = report.claims.map((claim) => `
    <article class="claim ${claim.effectiveStatus}">
      <div class="claim-top"><span class="status">${STATUS_ICON[claim.effectiveStatus]} ${escapeHtml(claim.effectiveStatus)}</span><span class="severity">${escapeHtml(claim.severity)}</span></div>
      <h2>${escapeHtml(claim.statement)}</h2>
      <p class="id">${escapeHtml(claim.id)}</p>
      ${claim.blockedBy.length ? `<p class="blocked">Blocked by: ${claim.blockedBy.map(escapeHtml).join(', ')}</p>` : ''}
      <div class="evidence">${claim.evidence.length ? claim.evidence.map((item) => `<div><b>${escapeHtml(item.id)}</b><span>${escapeHtml(item.verdict)} · ${escapeHtml(item.evidenceClass)}</span><p>${escapeHtml(item.summary)}</p><code>${escapeHtml(item.receiptHash.slice(0, 20))}…</code></div>`).join('') : '<div><p>No evidence configured.</p></div>'}</div>
      ${claim.limitations.length ? `<details><summary>Limitations</summary><ul>${claim.limitations.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul></details>` : ''}
    </article>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Proofspec — ${escapeHtml(report.project.name)}</title><style>
:root{color-scheme:dark;--bg:#080b12;--panel:#0e1420;--line:#273142;--text:#f5f7fb;--muted:#9ba6b7;--green:#53e6a7;--red:#ff8f96;--amber:#ffc66d;--violet:#a879ff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.6 system-ui,sans-serif}.wrap{width:min(1080px,calc(100% - 32px));margin:auto;padding:64px 0}header{padding-bottom:32px;border-bottom:1px solid var(--line)}h1{font-size:clamp(2.8rem,7vw,5.8rem);line-height:.95;letter-spacing:-.06em;margin:.5rem 0}.lede{color:var(--muted);max-width:700px}.summary{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;background:var(--line);border:1px solid var(--line);margin:32px 0}.summary div{background:var(--panel);padding:14px}.summary b{font-size:1.4rem;display:block}.summary span{color:var(--muted);font-size:.75rem}.claim{margin:14px 0;padding:20px;border:1px solid var(--line);border-left:4px solid var(--muted);border-radius:14px;background:var(--panel)}.claim.verified{border-left-color:var(--green)}.claim.failed{border-left-color:var(--red)}.claim.unknown{border-left-color:var(--amber)}.claim.blocked{border-left-color:var(--violet)}.claim-top{display:flex;justify-content:space-between;font-size:.72rem;text-transform:uppercase;letter-spacing:.08em}.status{font-weight:800}.severity,.id,code{color:var(--muted)}h2{margin:.8rem 0 .1rem;line-height:1.2}.id{margin:0;font-family:ui-monospace,monospace}.blocked{color:var(--violet)}.evidence{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px;margin-top:18px}.evidence>div{padding:12px;border:1px solid var(--line);border-radius:10px}.evidence b,.evidence span{display:block}.evidence span,.evidence p{color:var(--muted);font-size:.82rem}details{margin-top:16px;color:var(--muted)}footer{margin-top:40px;color:var(--muted);font-size:.75rem}@media(max-width:700px){.summary{grid-template-columns:1fr 1fr}}</style></head><body><main class="wrap"><header><small>EXECUTABLE CLAIM EVIDENCE</small><h1>${escapeHtml(report.project.name)}</h1><p class="lede">Gate <b>${report.summary.gatePassed ? 'passed' : 'failed'}</b> · ${escapeHtml(report.generatedAt)} · ledger ${report.ledger.valid ? 'valid' : 'invalid'} · digest ${escapeHtml(report.reportDigest.slice(0, 20))}…</p></header><section class="summary"><div><b>${report.summary.verified}</b><span>verified</span></div><div><b>${report.summary.failed}</b><span>failed</span></div><div><b>${report.summary.unknown}</b><span>unknown</span></div><div><b>${report.summary.unsupported}</b><span>unsupported</span></div><div><b>${report.summary.blocked}</b><span>blocked</span></div></section>${cards}<footer>Generated by Proofspec 0.1.0. A satisfied verifier proves only its configured observation.</footer></main></body></html>\n`;
}

function claimMarkdown(claim: ClaimResult): string[] {
  const lines = [
    `## ${STATUS_ICON[claim.effectiveStatus]} ${claim.id}`,
    '',
    claim.statement,
    '',
    `- Direct status: \`${claim.directStatus}\``,
    `- Effective status: \`${claim.effectiveStatus}\``,
    `- Severity: \`${claim.severity}\``,
    `- Policy: \`${claim.policy.mode}${claim.policy.mode === 'at_least' ? `:${claim.policy.count}` : ''}\``,
  ];
  if (claim.blockedBy.length) lines.push(`- Blocked by: ${claim.blockedBy.map((item) => `\`${item}\``).join(', ')}`);
  lines.push('', '### Evidence', '');
  if (!claim.evidence.length) lines.push('- No evidence configured.');
  for (const item of claim.evidence) {
    lines.push(`- **${item.id}** — \`${item.verdict}\` / \`${item.evidenceClass}\`: ${item.summary}  `, `  Receipt: \`${item.receiptHash}\``);
  }
  if (claim.limitations.length) lines.push('', '### Limitations', '', ...claim.limitations.map((item) => `- ${item}`));
  lines.push('');
  return lines;
}

function escapeMarkdown(value: string): string { return value.replaceAll('|', '\\|').replaceAll('\n', ' '); }
function escapeMermaid(value: string): string { return value.replaceAll('"', "'").replaceAll('\n', ' '); }
function nodeId(value: string): string { return `claim_${value.replace(/[^a-zA-Z0-9_]/g, '_')}`; }
function escapeHtml(value: string): string { return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;'); }
